"""empty message

Revision ID: 0ef68db15b01
Revises: 685d83e79a24
Create Date: 2022-08-11 14:34:41.382751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef68db15b01'
down_revision = '685d83e79a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
