"""empty message

Revision ID: 5ec05a39febe
Revises: 03b459f86a82
Create Date: 2022-08-11 13:53:40.496989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec05a39febe'
down_revision = '03b459f86a82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'state')
    op.drop_column('artist', 'city')
    op.drop_column('artist', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
