"""empty message

Revision ID: 685d83e79a24
Revises: 5ec05a39febe
Create Date: 2022-08-11 13:54:00.148457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685d83e79a24'
down_revision = '5ec05a39febe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('city', sa.String(), nullable=True))
    op.add_column('artist', sa.Column('state', sa.String(), nullable=True))
    op.add_column('artist', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'phone')
    op.drop_column('artist', 'state')
    op.drop_column('artist', 'city')
    # ### end Alembic commands ###
